version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      - image: mlabouardy/icinga2:test

    working_directory: /go/src/github.com/mlabouardy/icinga2-slack-bot

    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -v

      - run:
          name: Waiting for Icinga2 to be ready
          command: |
            sleep 20

      - run:
          name: Run vet command
          command: go vet ./...

      - run:
          name: Run unit tests
          environment:
            HOST_ICINGA: localhost
            USERNAME_ICINGA: root
            PASSWORD_ICINGA: icinga
          command: go test -v -race ./...
